FROM alpine:3.15

RUN apk update && \
    apk add --no-cache python3 py3-pip iputils ca-certificates net-snmp-tools \
      procps lm_sensors tzdata su-exec libcap && \
    update-ca-certificates

ENV TELEGRAF_VERSION 1.22.4

RUN set -ex && \
    FILE=telegraf-${TELEGRAF_VERSION}_linux_armhf.tar.gz && \
    mkdir ~/.gnupg; \
    echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf; \
    apk add --no-cache --virtual .build-deps wget gnupg tar && \
    for key in \
        05CE15085FC09D18E99EFB22684A14CF2582E0C5 ; \
    do \
        gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys "$key" ; \
    done && \
    wget --no-verbose https://dl.influxdata.com/telegraf/releases/${FILE}.asc && \
    wget --no-verbose https://dl.influxdata.com/telegraf/releases/${FILE} && \
    gpg --batch --verify ${FILE}.asc ${FILE} && \
    mkdir -p /usr/src /etc/telegraf && \
    tar -C /usr/src -xzf ${FILE} && \
    mv /usr/src/telegraf*/etc/telegraf/telegraf.conf /etc/telegraf/ && \
    mkdir /etc/telegraf/telegraf.d && \
    cp -a /usr/src/telegraf*/usr/bin/telegraf /usr/bin/ && \
    gpgconf --kill all && \
    rm -rf *.tar.gz* /usr/src /root/.gnupg && \
    apk del .build-deps && \
    addgroup -S telegraf && \
    adduser -S telegraf -G telegraf -G dialout && \
    chown -R telegraf:telegraf /etc/telegraf

RUN python3 -m pip install --no-cache dsmr_parser
COPY ./dsmr.py /home/telegraf/dsmr.py

EXPOSE 8125/udp 8092/udp 8094

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["telegraf"]

